services:
  postgres:
    image: postgres:16
    container_name: restaurant-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: restaurant_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: restaurant-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: restaurant-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: